name: main

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Init
      - name: init
        uses: Mafalda-SFU/Github-Actions-init@v1
        with:
          node-version: lts/-1

      # Ensure extracted tests are working
      - name: Run tests
        run: npm test
